# [Forward propagation](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.linkedin.com%2Fpulse%2Fdemystifying-forward-propagation-neural-networks-real-world-v&psig=AOvVaw0CPn8hGRmz45qJSm_HMu5L&ust=1717158871659000&source=images&cd=vfe&opi=89978449&ved=0CBQQjhxqFwoTCIj5p7yxtYYDFQAAAAAdAAAAABAE)

When working with a neural network we see that I does training and after training it does predictions. Behind the scenes it does two things:  
* [Forward propagation](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.linkedin.com%2Fpulse%2Fdemystifying-forward-propagation-neural-networks-real-world-v&psig=AOvVaw0CPn8hGRmz45qJSm_HMu5L&ust=1717158871659000&source=images&cd=vfe&opi=89978449&ved=0CBQQjhxqFwoTCIj5p7yxtYYDFQAAAAAdAAAAABAE)  
* Backward propagation  

When we are making prediction from the model it only does forward propagation but when we are training a model it does both.  
During training it first does forward propagation and then it does back propagation. Through backward propagation it can update the weights.  
Backward propagation is a little complex so we will cover it in another tutorial but lets first look at the forward propagation.

## [Forward propagation](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.linkedin.com%2Fpulse%2Fdemystifying-forward-propagation-neural-networks-real-world-v&psig=AOvVaw0CPn8hGRmz45qJSm_HMu5L&ust=1717158871659000&source=images&cd=vfe&opi=89978449&ved=0CBQQjhxqFwoTCIj5p7yxtYYDFQAAAAAdAAAAABAE) (or forward pass) 
Forward propagation refers to the calculation and storage of intermediate variables (including outputs) for a neural network in order from the input layer to the output layer.

You can see forward propagation in the image below 
 
![Forward Propagaton](https://media.licdn.com/dms/image/D5612AQE5LhqHLhJ2gg/article-cover_image-shrink_600_2000/0/1696319165807?e=2147483647&v=beta&t=6433lXyliKAbR75zYbOeeBjIy43vReRvnXphYLrl5XA)

In [31]:
# Importing the numpy library(used for vector manipulation)
import numpy as np

In [19]:
# Input data
x = np.array([200,17])
x.shape

(2,)

Our input for the model contains 2 values 200 and 17. So our input layer should also have 2 neurons.

In [8]:
# Creating the sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

After creating the sigmoid function lets create the first layer of our neural network.  

Our first layer neuron will contain 3 neurons. Every nueron will get the input data that we created ans every nueron will have its own parameters(weights, bias).

In [20]:
# Parameters for first neuron of first layer
w1_1 = np.array([1,2])
b1_1 = np.array([-1])

# Computing the z1_1 and a1_1 using the dot product
z1_1 = np.dot(w1_1,x) + b1_1
a1_1 = sigmoid(z1_1)
a1_1

array([1.])

In [21]:
# Parameters for second neuron fo first layer
w1_2 = np.array([-3,4])
b1_2 = np.array([1])

# Computing the z1_2 and a1_2 using the dot product
z1_2 = np.dot(w1_2,x) + b1_2
a1_2 = sigmoid(z1_2)
a1_2

array([2.45261912e-231])

In [22]:
# Parameters for the third neuron of first layer
w1_3 = np.array([5,-6])
b1_3 = np.array([2])

# Computing the z1_3 and a1_3 using the dot product
z1_3 = np.dot(w1_3,x) + b1_3
a1_3 = sigmoid(z1_3)
a1_3

array([1.])

In [23]:
# now lets conbine the result from the first layer into a list that will be passed to the next layer(second layer in our case)
a1 = np.array([a1_1,a1_2,a1_3])
a1

array([[1.00000000e+000],
       [2.45261912e-231],
       [1.00000000e+000]])

Now we will create the second layer of our neural network. We will add only neuron in it.  
It will take the input from the previous layer(which is a list of 3 values) and it will have 3 weights and 1 bias.  
Then it will calculate a single value

In [13]:
# Parameters for first neuron of second layer
w2_1 = np.array([-7,8,9])
b2_1 = np.array([3])

# Computing the z2_1 and a2_1
z2_1 = np.dot(w2_1,a1) + b2_1
a2_1 = sigmoid(z2_1)
a2_1

array([0.99330715])

Here is the result from our forward propagation neural network

Now lets sum it up by creating a function that will do all of this

In [37]:
W = np.array([[ 1, -3,  5],
              [ -2,  4, -6]])
B = np.array([[-1,1,2]])
W.shape, B.shape

((2, 3), (1, 3))

In [16]:
# Now lets impliment the forward propagation in a more general way rather than hardcoding the values
def dense(a_in,W,b):
    z = np.matmul(a_in, W) + B
    a_out = sigmoid(z)
    return a_out    
        

In [17]:
# Calling the function on the parameters and imput data that we have created.
dense(x,W,B)

array([[1.00000000e+000, 2.45261912e-231, 1.00000000e+000]])

Thank for reading.

Untill next time  
Allah Hafiz